package org.aplication.backend.common.constants;

import lombok.Getter;
import org.springframework.http.HttpStatus;

/** Stable business error catalog. Message text is resolved from i18n resources. */
@Getter
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "error.uncategorized", HttpStatus.INTERNAL_SERVER_ERROR),
    VALIDATION_FAILED(1000, "VALIDATION_FAILED", HttpStatus.BAD_REQUEST),
    DATA_CONFLICT(1001, "DATA_CONFLICT", HttpStatus.CONFLICT),
    RESOURCE_NOT_FOUND(1002, "RESOURCE_NOT_FOUND", HttpStatus.NOT_FOUND),
    FORBIDDEN(1003, "FORBIDDEN", HttpStatus.FORBIDDEN),
    INVALID_STATE_TRANSITION(1004, "INVALID_STATE_TRANSITION", HttpStatus.CONFLICT),
    REQUEST_IDEMPOTENCY_CONFLICT(1005, "REQUEST_IDEMPOTENCY_CONFLICT", HttpStatus.CONFLICT),

    AUTH_INVALID_CREDENTIALS(1100, "AUTH_INVALID_CREDENTIALS", HttpStatus.UNAUTHORIZED),
    AUTH_INVALID_TOKEN(1101, "AUTH_INVALID_TOKEN", HttpStatus.UNAUTHORIZED),
    AUTH_EMAIL_EXISTS(1102, "AUTH_EMAIL_EXISTS", HttpStatus.CONFLICT),
    AUTH_PHONE_EXISTS(1103, "AUTH_PHONE_EXISTS", HttpStatus.CONFLICT),
    AUTH_REGISTRATION_NOT_FOUND(1104, "AUTH_REGISTRATION_NOT_FOUND", HttpStatus.BAD_REQUEST),
    AUTH_OTP_INVALID(1105, "AUTH_OTP_INVALID", HttpStatus.UNAUTHORIZED),
    AUTH_OTP_SERVICE_UNAVAILABLE(1106, "AUTH_OTP_SERVICE_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE),
    AUTH_ACCOUNT_INACTIVE(1107, "AUTH_ACCOUNT_INACTIVE", HttpStatus.FORBIDDEN),
    AUTH_ROLE_NOT_ALLOWED(1108, "AUTH_ROLE_NOT_ALLOWED", HttpStatus.FORBIDDEN),

    BUSINESS_PROFILE_NOT_FOUND(2000, "BUSINESS_PROFILE_NOT_FOUND", HttpStatus.NOT_FOUND),
    HALL_NOT_FOUND(2001, "HALL_NOT_FOUND", HttpStatus.NOT_FOUND),
    HALL_INACTIVE(2002, "HALL_INACTIVE", HttpStatus.CONFLICT),
    HALL_CAPACITY_EXCEEDED(2003, "HALL_CAPACITY_EXCEEDED", HttpStatus.CONFLICT),
    DISH_NOT_FOUND(2100, "DISH_NOT_FOUND", HttpStatus.NOT_FOUND),
    DISH_INACTIVE(2101, "DISH_INACTIVE", HttpStatus.CONFLICT),
    MENU_PACKAGE_NOT_FOUND(2102, "MENU_PACKAGE_NOT_FOUND", HttpStatus.NOT_FOUND),
    MENU_PACKAGE_INVALID(2103, "MENU_PACKAGE_INVALID", HttpStatus.CONFLICT),

    ORDER_NOT_FOUND(3000, "ORDER_NOT_FOUND", HttpStatus.NOT_FOUND),
    ORDER_INVALID_TIME_RANGE(3001, "ORDER_INVALID_TIME_RANGE", HttpStatus.BAD_REQUEST),
    ORDER_HALL_UNAVAILABLE(3002, "ORDER_HALL_UNAVAILABLE", HttpStatus.CONFLICT),
    ORDER_EMPTY_ITEMS(3003, "ORDER_EMPTY_ITEMS", HttpStatus.BAD_REQUEST),
    ORDER_INVALID_STATUS(3004, "ORDER_INVALID_STATUS", HttpStatus.CONFLICT),
    ORDER_CHANGE_NOT_ALLOWED(3005, "ORDER_CHANGE_NOT_ALLOWED", HttpStatus.CONFLICT),
    ORDER_CANCEL_NOT_ALLOWED(3006, "ORDER_CANCEL_NOT_ALLOWED", HttpStatus.CONFLICT),
    ORDER_CHANGE_REQUEST_NOT_FOUND(3007, "ORDER_CHANGE_REQUEST_NOT_FOUND", HttpStatus.NOT_FOUND),

    PAYMENT_NOT_FOUND(4000, "PAYMENT_NOT_FOUND", HttpStatus.NOT_FOUND),
    PAYMENT_AMOUNT_INVALID(4001, "PAYMENT_AMOUNT_INVALID", HttpStatus.BAD_REQUEST),
    PAYMENT_ALREADY_COMPLETED(4002, "PAYMENT_ALREADY_COMPLETED", HttpStatus.CONFLICT),
    PAYMENT_PROVIDER_FAILED(4003, "PAYMENT_PROVIDER_FAILED", HttpStatus.BAD_GATEWAY),
    PAYMENT_SIGNATURE_INVALID(4004, "PAYMENT_SIGNATURE_INVALID", HttpStatus.BAD_REQUEST),
    PAYMENT_REFUND_NOT_ALLOWED(4005, "PAYMENT_REFUND_NOT_ALLOWED", HttpStatus.CONFLICT),

    UNIT_NOT_FOUND(5000, "UNIT_NOT_FOUND", HttpStatus.NOT_FOUND),
    INGREDIENT_NOT_FOUND(5001, "INGREDIENT_NOT_FOUND", HttpStatus.NOT_FOUND),
    INGREDIENT_INACTIVE(5002, "INGREDIENT_INACTIVE", HttpStatus.CONFLICT),
    SUPPLIER_NOT_FOUND(5003, "SUPPLIER_NOT_FOUND", HttpStatus.NOT_FOUND),
    BATCH_NOT_FOUND(5004, "BATCH_NOT_FOUND", HttpStatus.NOT_FOUND),
    QUALITY_CRITERIA_NOT_MET(5005, "QUALITY_CRITERIA_NOT_MET", HttpStatus.CONFLICT),
    INSUFFICIENT_STOCK(5006, "INSUFFICIENT_STOCK", HttpStatus.CONFLICT),
    STOCK_NEGATIVE_NOT_ALLOWED(5007, "STOCK_NEGATIVE_NOT_ALLOWED", HttpStatus.CONFLICT),
    STOCK_RESERVATION_NOT_FOUND(5008, "STOCK_RESERVATION_NOT_FOUND", HttpStatus.NOT_FOUND),
    STOCK_MOVEMENT_IMMUTABLE(5009, "STOCK_MOVEMENT_IMMUTABLE", HttpStatus.CONFLICT),

    SHIFT_NOT_FOUND(6000, "SHIFT_NOT_FOUND", HttpStatus.NOT_FOUND),
    SHIFT_CONFLICT(6001, "SHIFT_CONFLICT", HttpStatus.CONFLICT),
    SHIFT_REQUEST_NOT_FOUND(6002, "SHIFT_REQUEST_NOT_FOUND", HttpStatus.NOT_FOUND),
    SHIFT_REQUEST_ALREADY_REVIEWED(6003, "SHIFT_REQUEST_ALREADY_REVIEWED", HttpStatus.CONFLICT),
    TASK_NOT_FOUND(6100, "TASK_NOT_FOUND", HttpStatus.NOT_FOUND),
    TASK_NOT_ASSIGNED(6101, "TASK_NOT_ASSIGNED", HttpStatus.FORBIDDEN),
    TASK_INVALID_STATUS(6102, "TASK_INVALID_STATUS", HttpStatus.CONFLICT),

    PAY_RATE_NOT_FOUND(7000, "PAY_RATE_NOT_FOUND", HttpStatus.NOT_FOUND),
    PAYROLL_PERIOD_NOT_FOUND(7001, "PAYROLL_PERIOD_NOT_FOUND", HttpStatus.NOT_FOUND),
    PAYROLL_ALREADY_APPROVED(7002, "PAYROLL_ALREADY_APPROVED", HttpStatus.CONFLICT),
    SALARY_PAYMENT_ALREADY_RECORDED(7003, "SALARY_PAYMENT_ALREADY_RECORDED", HttpStatus.CONFLICT);

    private final int code;
    private final String messageKey;
    private final HttpStatus statusCode;

    ErrorCode(int code, String messageKey, HttpStatus statusCode) {
        this.code = code;
        this.messageKey = messageKey;
        this.statusCode = statusCode;
    }
}
